// User 
export const DO_SIGNUP = 'DO_SIGNUP'
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE'

// Student review
export const CREATE_USER_REVIEW = 'CREATE_USER_REVIEW'
export const UPDATE_USER_REVIEW = 'UPDATE_USER_REVIEW'
export const DELETE_USER_REVIEW = 'DELETE_USER_REVIEW'

// Senior
export const CREATE_SENIOR_PROFILE = 'CREATE_SENIOR_PROFILE'
export const UPDATE_SENIOR_PROFILE = 'UPDATE_SENIOR_PROFILE' 

// Class setup
export const CREATE_CLASS = 'CREATE_CLASS'
export const UPDATE_CLASS = 'UPDATE_CLASS'
export const DELETE_CLASS = 'DELETE_CLASS'

// Class review
export const CREATE_CLASS_REVIEW = 'CREATE_CLASS_REVIEW'
export const UPDATE_CLASS_REVIEW = 'UPDATE_CLASS_REVIEW'
export const DELETE_CLASS_REVIEW = 'DELETE_CLASS_REVIEW'

// Data retrieval
export const GET_ALL_CLASSES = 'GET_ALL_CLASSES'
export const GET_CLASSES_BY_CATEGORY = 'GET_CLASES_BY_CATEGORY'
export const GET_CLASS_INFORMATION = 'GET_CLASS_INFORMATION'

// Appointment
export const SIGN_UP_FOR_CLASS = 'SIGN_UP_FOR_CLASS'
export const CANCEL_EXISTING_APPOINTMENT = 'CANCEL_EXISTING_APPOINTMENT' 
export const CHANGE_APPOINTMENT_DETAILS = 'CHANGE_APPOINTMENT_DETAILS' 

// Login
export const LOGIN_TYPE = 'LOGIN_TYPE'
export const DO_USER_LOGIN = 'DO_USER_LOGIN'
export const DO_SENIOR_LOGIN = 'DO_SENIOR_LOGIN'